import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-purchase-order-receipt-invoice-quantity-recovery",
  "engine": "recovery",
  "title": "Purchase Order, Receipt & Invoice Quantity Recovery",
  "shortTitle": "Purchase Order, Receipt and Invoice Quantity Recovery",
  "tagline": "Recover invoice overpayments caused by quantity, receipt, return, unit-of-measure, and tolerance mismatches.",
  "industry": "Procurement Payment Integrity",
  "buyer": "Enterprise procurement and accounts-payable teams",
  "uiPort": 4701,
  "apiPort": 5701,
  "accent": "#4f46e5",
  "currency": "USD",
  "primaryOutcome": "Purchase Order, Receipt & Invoice Quantity Recovery converted into governed, evidence-backed financial outcomes",
  "valueNarrative": "Connect purchase orders, releases, receipts, service entries, returns, invoices, units of measure, tolerances, payments, and credits in one accountable workflow. Recover invoice overpayments caused by quantity, receipt, return, unit-of-measure, and tolerance mismatches.",
  "calculation": {
    "actualKey": "chargedAmount",
    "expectedKey": "supportedAmount",
    "actualLabel": "Charged or Paid Amount",
    "expectedLabel": "Evidence-Supported Amount",
    "varianceLabel": "Potential recovery or avoided cost",
    "direction": "actual-minus-expected",
    "finding": "Purchase Order, Receipt & Invoice Quantity Recovery evidence indicates a measurable financial exception.",
    "actions": [
      "Validate the effective agreement, eligibility rules, and accountable parties",
      "Reconcile transaction-level operational and financial evidence",
      "Prepare the correction, recovery, or compliance package",
      "Track counterparty response, approval, cash, and preventive control closure"
    ]
  }
},[
feature("purchase-order-ingestion","POR01","Purchase order ingestion","Execute purchase order ingestion using purchase orders, releases, receipts, service entries, returns, invoices, units of measure, tolerances, payments, and credits.","Produce a governed purchase order ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Purchase Order","text","Supplier / Purchase Order · Standard Case"],["caseReference","Purchase order ingestion Reference","text","POR01-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1305000],["supportedAmount","Evidence-Supported Amount","currency",1096200],["domainDriver","Mismatch Type","select","Overbilling",["Overbilling","Short receipt","Unit conversion"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Purchase order ingestion case","Release schedule control case","Goods receipt matching case","Service entry validation case","Return-to-vendor linkage case"]}),
feature("release-schedule-control","POR02","Release schedule control","Execute release schedule control using purchase orders, releases, receipts, service entries, returns, invoices, units of measure, tolerances, payments, and credits.","Produce a governed release schedule control decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Purchase Order","text","Supplier / Purchase Order · Standard Case"],["caseReference","Release schedule control Reference","text","POR02-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1305000],["supportedAmount","Evidence-Supported Amount","currency",1096200],["domainDriver","Mismatch Type","select","Overbilling",["Overbilling","Short receipt","Unit conversion"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Purchase order ingestion case","Release schedule control case","Goods receipt matching case","Service entry validation case","Return-to-vendor linkage case"]}),
feature("goods-receipt-matching","POR03","Goods receipt matching","Execute goods receipt matching using purchase orders, releases, receipts, service entries, returns, invoices, units of measure, tolerances, payments, and credits.","Produce a governed goods receipt matching decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Purchase Order","text","Supplier / Purchase Order · Standard Case"],["caseReference","Goods receipt matching Reference","text","POR03-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1305000],["supportedAmount","Evidence-Supported Amount","currency",1096200],["domainDriver","Mismatch Type","select","Overbilling",["Overbilling","Short receipt","Unit conversion"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Purchase order ingestion case","Release schedule control case","Goods receipt matching case","Service entry validation case","Return-to-vendor linkage case"]}),
feature("service-entry-validation","POR04","Service entry validation","Execute service entry validation using purchase orders, releases, receipts, service entries, returns, invoices, units of measure, tolerances, payments, and credits.","Produce a governed service entry validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Purchase Order","text","Supplier / Purchase Order · Standard Case"],["caseReference","Service entry validation Reference","text","POR04-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1305000],["supportedAmount","Evidence-Supported Amount","currency",1096200],["domainDriver","Mismatch Type","select","Overbilling",["Overbilling","Short receipt","Unit conversion"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Purchase order ingestion case","Release schedule control case","Goods receipt matching case","Service entry validation case","Return-to-vendor linkage case"]}),
feature("return-to-vendor-linkage","POR05","Return-to-vendor linkage","Execute return-to-vendor linkage using purchase orders, releases, receipts, service entries, returns, invoices, units of measure, tolerances, payments, and credits.","Produce a governed return-to-vendor linkage decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Purchase Order","text","Supplier / Purchase Order · Standard Case"],["caseReference","Return-to-vendor linkage Reference","text","POR05-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1305000],["supportedAmount","Evidence-Supported Amount","currency",1096200],["domainDriver","Mismatch Type","select","Overbilling",["Overbilling","Short receipt","Unit conversion"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Purchase order ingestion case","Release schedule control case","Goods receipt matching case","Service entry validation case","Return-to-vendor linkage case"]}),
feature("invoice-line-ingestion","POR06","Invoice line ingestion","Execute invoice line ingestion using purchase orders, releases, receipts, service entries, returns, invoices, units of measure, tolerances, payments, and credits.","Produce a governed invoice line ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Purchase Order","text","Supplier / Purchase Order · Standard Case"],["caseReference","Invoice line ingestion Reference","text","POR06-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1305000],["supportedAmount","Evidence-Supported Amount","currency",1096200],["domainDriver","Mismatch Type","select","Overbilling",["Overbilling","Short receipt","Unit conversion"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Purchase order ingestion case","Release schedule control case","Goods receipt matching case","Service entry validation case","Return-to-vendor linkage case"]}),
feature("unit-of-measure-conversion","POR07","Unit-of-measure conversion","Execute unit-of-measure conversion using purchase orders, releases, receipts, service entries, returns, invoices, units of measure, tolerances, payments, and credits.","Produce a governed unit-of-measure conversion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Purchase Order","text","Supplier / Purchase Order · Standard Case"],["caseReference","Unit-of-measure conversion Reference","text","POR07-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1305000],["supportedAmount","Evidence-Supported Amount","currency",1096200],["domainDriver","Mismatch Type","select","Overbilling",["Overbilling","Short receipt","Unit conversion"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Purchase order ingestion case","Release schedule control case","Goods receipt matching case","Service entry validation case","Return-to-vendor linkage case"]}),
feature("quantity-tolerance-control","POR08","Quantity tolerance control","Execute quantity tolerance control using purchase orders, releases, receipts, service entries, returns, invoices, units of measure, tolerances, payments, and credits.","Produce a governed quantity tolerance control decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Purchase Order","text","Supplier / Purchase Order · Standard Case"],["caseReference","Quantity tolerance control Reference","text","POR08-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1305000],["supportedAmount","Evidence-Supported Amount","currency",1096200],["domainDriver","Mismatch Type","select","Overbilling",["Overbilling","Short receipt","Unit conversion"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Purchase order ingestion case","Release schedule control case","Goods receipt matching case","Service entry validation case","Return-to-vendor linkage case"]}),
feature("duplicate-receipt-detection","POR09","Duplicate receipt detection","Execute duplicate receipt detection using purchase orders, releases, receipts, service entries, returns, invoices, units of measure, tolerances, payments, and credits.","Produce a governed duplicate receipt detection decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Purchase Order","text","Supplier / Purchase Order · Standard Case"],["caseReference","Duplicate receipt detection Reference","text","POR09-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1305000],["supportedAmount","Evidence-Supported Amount","currency",1096200],["domainDriver","Mismatch Type","select","Overbilling",["Overbilling","Short receipt","Unit conversion"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Purchase order ingestion case","Release schedule control case","Goods receipt matching case","Service entry validation case","Return-to-vendor linkage case"]}),
feature("short-shipment-analysis","POR10","Short shipment analysis","Execute short shipment analysis using purchase orders, releases, receipts, service entries, returns, invoices, units of measure, tolerances, payments, and credits.","Produce a governed short shipment analysis decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Purchase Order","text","Supplier / Purchase Order · Standard Case"],["caseReference","Short shipment analysis Reference","text","POR10-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1305000],["supportedAmount","Evidence-Supported Amount","currency",1096200],["domainDriver","Mismatch Type","select","Overbilling",["Overbilling","Short receipt","Unit conversion"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Purchase order ingestion case","Release schedule control case","Goods receipt matching case","Service entry validation case","Return-to-vendor linkage case"]}),
feature("three-way-match-calculation","POR11","Three-way match calculation","Execute three-way match calculation using purchase orders, releases, receipts, service entries, returns, invoices, units of measure, tolerances, payments, and credits.","Produce a governed three-way match calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Purchase Order","text","Supplier / Purchase Order · Standard Case"],["caseReference","Three-way match calculation Reference","text","POR11-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1305000],["supportedAmount","Evidence-Supported Amount","currency",1096200],["domainDriver","Mismatch Type","select","Overbilling",["Overbilling","Short receipt","Unit conversion"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Purchase order ingestion case","Release schedule control case","Goods receipt matching case","Service entry validation case","Return-to-vendor linkage case"]}),
feature("payment-overage-detection","POR12","Payment overage detection","Execute payment overage detection using purchase orders, releases, receipts, service entries, returns, invoices, units of measure, tolerances, payments, and credits.","Produce a governed payment overage detection decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Purchase Order","text","Supplier / Purchase Order · Standard Case"],["caseReference","Payment overage detection Reference","text","POR12-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1305000],["supportedAmount","Evidence-Supported Amount","currency",1096200],["domainDriver","Mismatch Type","select","Overbilling",["Overbilling","Short receipt","Unit conversion"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Purchase order ingestion case","Release schedule control case","Goods receipt matching case","Service entry validation case","Return-to-vendor linkage case"]}),
feature("supplier-claim-workflow","POR13","Supplier claim workflow","Execute supplier claim workflow using purchase orders, releases, receipts, service entries, returns, invoices, units of measure, tolerances, payments, and credits.","Produce a governed supplier claim workflow decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Purchase Order","text","Supplier / Purchase Order · Standard Case"],["caseReference","Supplier claim workflow Reference","text","POR13-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1305000],["supportedAmount","Evidence-Supported Amount","currency",1096200],["domainDriver","Mismatch Type","select","Overbilling",["Overbilling","Short receipt","Unit conversion"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Purchase order ingestion case","Release schedule control case","Goods receipt matching case","Service entry validation case","Return-to-vendor linkage case"]}),
feature("credit-reconciliation","POR14","Credit reconciliation","Execute credit reconciliation using purchase orders, releases, receipts, service entries, returns, invoices, units of measure, tolerances, payments, and credits.","Produce a governed credit reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Purchase Order","text","Supplier / Purchase Order · Standard Case"],["caseReference","Credit reconciliation Reference","text","POR14-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1305000],["supportedAmount","Evidence-Supported Amount","currency",1096200],["domainDriver","Mismatch Type","select","Overbilling",["Overbilling","Short receipt","Unit conversion"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Purchase order ingestion case","Release schedule control case","Goods receipt matching case","Service entry validation case","Return-to-vendor linkage case"]}),
feature("buyer-supplier-analytics","POR15","Buyer supplier analytics","Execute buyer supplier analytics using purchase orders, releases, receipts, service entries, returns, invoices, units of measure, tolerances, payments, and credits.","Produce a governed buyer supplier analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Purchase Order","text","Supplier / Purchase Order · Standard Case"],["caseReference","Buyer supplier analytics Reference","text","POR15-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1305000],["supportedAmount","Evidence-Supported Amount","currency",1096200],["domainDriver","Mismatch Type","select","Overbilling",["Overbilling","Short receipt","Unit conversion"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Purchase order ingestion case","Release schedule control case","Goods receipt matching case","Service entry validation case","Return-to-vendor linkage case"]})
]);
